<div class='inkifi-map'>
	<section>
		<div class='ikf-left'>
			<h1>Mappy Place</h1>
			<div class='ikf-subtitle e1'>Create and customise city map prints of anywhere in the world</div>
			<div class='ikf-subtitle e2'>Free And Fast UK Delivery</div>
			<a class='ikf-create' href='javascript:void(0)'>Create Your Poster</a>
		</div>
		<div class='ikf-right'>
		</div>
	</section>
	<section>
		<ol class='ikf-benefits'>
			<li>
				<div class='ikf-figure'><?= df_block_output(null, 'Inkifi_Map::i/shipping.phtml') ?></div>
				<div>Fast shipping, worldwide</div>
			</li>
			<li>
				<div class='ikf-figure'>
					<?= df_tag('img', ['src' => df_asset_url('Inkifi_Map::i/index/print.svg')]) ?>
				</div>
				<div>Premium Quality Prints</div>
			</li>
			<li>
				<div class='ikf-figure'><?= df_block_output(null, 'Inkifi_Map::i/guarantee.phtml') ?></div>
				<div>100% Satisfaction Guarantee</div>
			</li>
		</ol>
		<h2>Create Your Poster</h2>
		<div class='ikf-cities'>
			<?=
				df_cc_n(df_map(function($c) {return
					df_tag('a', ['href' => 'javascript:void(0)'],
						df_tag('img', ['src' => df_asset_url("Inkifi_Map::i/index/map/$c.jpg")])
					)
				;}, ['new-york', 'singapore', 'copenhagen', 'paris', 'lisbon', 'london', 'amsterdam']));
			?>
		</div>
		<div class='ikf-button-container'>
			<a class='ikf-create' href='javascript:void(0)'>Create Poster</a>
		</div>
	</section>
	<section>
		<div class='ikf-left'>
			<h2>Customers Say</h2>
			<article>
				<div class='ikf-content'>How lovely is it to have art work around your home that evoke such good memories? Our new custom photo map print from @mappyplace_ makes me smile every time remembering good times we have spent there!</div>
				<a class='ikf-author' href='https://www.instagram.com/p/BxNkPCgF_C5'>@raising_5 on Instagram</a>
			</article>
		</div>
		<div class='ikf-right'>
			<a href='javascript:void(0)'>More inspiration</a>
		</div>
	</section>
</div>
<?= df_js_x('.inkifi-map', 'Inkifi_Map', 'index'); ?>
