<footer class='ikf-footer'>
	<div class='ikf-row'>
		<div class='ikf-column'>
			<h4>Support</h4>
			<ul>
				<li><a href='mailto:hello@mappyplace.com'>hello@mappyplace.com</a></li>
				<li>MappyPlace, Beehive Mill</li>
				<li>Jersey St, Manchester, M4 6JG</li>
			</ul>
		</div>
		<div class='ikf-column'>
			<h4>Follow Us</h4>
			<ul>
				<li><a href='https://www.instagram.com/mappyplace_'>Instagram</a></li>
				<li><a href='https://www.facebook.com/mymappyplace'>Facebook</a</li>
				<li><a href='https://twitter.com/mappyplace'>Twitter</a></li>
			</ul>
		</div>
		<div class='ikf-column'>
			<h4>Newsletter</h4>
			<form action='/' method='post'>
				<div>
					<input type='email'/>
					<div>Your email</div>					
				</div>
				<button>Send</button>
			</form>
			<p>Stay connected to be the first to know about discounts and promotions.</p>
		</div>
	</div>
	<div class='ikf-row'></div>
</footer>