<div class='ikf-header'>
	<div class='ikf-logo ikf-animation'>
		<a href='javascript:void(0)'>
			<figure><?= df_block_output(null, 'Inkifi_Map::common/i/logo.phtml') ?></figure>
			<span>mappy place</span>
		</a>
	</div>
	<div class='ikf-menu ikf-animation'>
		<div>
			<a href='javascript:void(0)'>About</a>
			<a href='javascript:void(0)'>Inspiration</a>
			<a href='javascript:void(0)'>#Mappyplace</a>
			<a href='javascript:void(0)'>Support</a>
			<a href='javascript:void(0)'>Contact</a>
		</div>
	</div>
	<div class='ikf-right'></div>
</div>