<svg 
	height='21'
	viewBox='0 0 19 21'
	width='19' 
	xmlns:xlink='http://www.w3.org/1999/xlink' 
	xmlns='http://www.w3.org/2000/svg' 
>
	<defs>
		<path
			d='M1069 31.5a2.5 2.5 0 1 1 5 0 2.5 2.5 0 0 1-5 0zm8 0a2.5 2.5 0 1 1 5 0 2.5 2.5 0 0 1-5 0zm-9-14.5s-3 0-3-3c0-.503 4 0 4 0l2 4 13 1-2 7-12 1z'
			id='pxnea'
		></path>
	</defs>
	<g>
		<g transform='translate(-1065 -13)'>
			<use xlink:href='#pxnea'></use>
		</g>
	</g>
</svg>