<article>
	<div class='ikf-zoom'>
		<div>
			<button><?= df_block_output(null, 'Inkifi_Map::i/create/zoom/plus.phtml') ?></button>
			<button><?= df_block_output(null, 'Inkifi_Map::i/create/zoom/minus.phtml') ?></button>
		</div>
	</div>
	<div class='ikf-map-1 ikf-ratio-3x4'> <!-- 2019-08-04 Original: `div#preview` -->
		<div class='ikf-pencil ikf-ratio-3x4'></div>
		<div class='ikf-map-2'>  <!-- 2019-08-04 Original: `div.b-editor-map__map-wrap` -->
			<div class='ikf-map-3'>  <!-- 2019-08-04 Original: `div.b-editor-map__map` -->
<!-- 
2019-08-04 Original: `div#mapbox-map`
2019-08-24 https://github.com/dmitry-fedyuk/inkifi-mappyplace/blob/2019-07-02/src/components/pages/Editor.js#L269-L271 -->
				<div class='ikf-map-4'></div>
			</div>
		</div>
		<div class='ikf-label'> <!-- 2019-08-04 Original: `.b-editor-map__desc` -->
			<h3 data-bind='text: posS'></h3>
			<div>
				<h1>London</h1>
				<h2>United Kingdom</h2>
			</div>
		</div>
	</div>
	<div class='ikf-mobile-hint'>You can <span>drag and zoom</span> map using standard gestures</div>
</article>