<article>
	<div class='ikf-zoom'>
		<div>
			<button><?= df_block_output(null, 'Inkifi_Map::create/i/zoom/plus.phtml') ?></button>
			<button><?= df_block_output(null, 'Inkifi_Map::create/i/zoom/minus.phtml') ?></button>
		</div>
	</div>
	<div class='ikf-map-1 ikf-ratio-3x4'> <!-- 2019-08-04 Original: `div#preview` -->
		<div class='ikf-pencil ikf-ratio-3x4'></div>
		<div class='ikf-map-2'>  <!-- 2019-08-04 Original: `div.b-editor-map__map-wrap` -->
			<div class='ikf-map-3'>  <!-- 2019-08-04 Original: `div.b-editor-map__map` -->
				<div class='ikf-map-4'> <!-- 2019-08-04 Original: `div#mapbox-map` -->
					<div class='ikf-map-5'> <!-- 2019-08-04 Original: `<div style='...'>` -->
						<div class='ikf-map-6'> <!-- 2019-08-04 Original: `<div style='...'>` -->
							<div class='ikf-map-7'> <!-- 2019-08-04 Original: `div.mapboxgl-map` -->
								<div class='ikf-canary'></div> <!-- 2019-08-04 Original: `div.mapboxgl-canary` -->
								<!-- 2019-08-04 Original: `div.mapboxgl-canvas-container` -->
								<div>
									<canvas></canvas>
								</div>
								<!-- 2019-08-04 Original: `div.mapboxgl-control-container` -->
								<div class='ikf-controls'>
									<div class='ikf-top-left'></div>
									<div class='ikf-top-right'></div>
									<div class='ikf-bottom-left'>
										<div class='ikf-control'>
											<a
												aria-label='Mapbox logo'
												href='https://www.mapbox.com'
												rel='noopener'
												target='_blank'
											></a>
										</div>
									</div>
									<div class='ikf-bottom-right'>
										<div class='ikf-control'>
											<div></div>
										</div>
									</div>
								</div>
							</div>
							<!-- 2019-08-04 Original: `<div style='overflow: visible; ...'>` -->
							<div class='ikf-overlay'>
								<div></div> <!-- 2019-08-04 Original: `div.overlays` -->
							</div>
							<div class='ikf-resize'> <!-- 2019-08-04 Original: `div.resize-triggers` -->
								<div class='ikf-expand'> <!-- 2019-08-04 Original: `div.expand-trigger` -->
									<div></div>
								</div>
								<!-- 2019-08-04 Original: `div.contract-trigger` -->
								<div class='ikf-contract'></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class='ikf-label'> <!-- 2019-08-04 Original: `.b-editor-map__desc` -->
			<h3>51.496°N/-0.077°E</h3>
			<div class='ikf-name'>London<div>United Kingdom</div></div>
		</div>
	</div>
	<div class='ikf-mobile-hint'>You can <span>drag and zoom</span> map using standard gestures</div>
</article>