<article>
	<div class='ikf-zoom'>
		<div>
			<button><?= df_block_output(null, 'Inkifi_Map::create/i/zoom/plus.phtml') ?></button>
			<button><?= df_block_output(null, 'Inkifi_Map::create/i/zoom/minus.phtml') ?></button>
		</div>
	</div>
	<div class='ikf-map-1'> <!-- 2019-08-04 Original: `div#preview` -->
		<div class='ikf-pencil'></div>
		<div class='ikf-map-2'>  <!-- 2019-08-04 Original: `div.b-editor-map__map-wrap` -->
			<div class='ikf-map-3'>  <!-- 2019-08-04 Original: `div.b-editor-map__map` -->
				<div class='ikf-map-4'> <!-- 2019-08-04 Original: `div#mapbox-map` -->
					<div class='ikf-map-5'> <!-- 2019-08-04 Original: `<div style='...'>` -->
						<div class='ikf-map-6'> <!-- 2019-08-04 Original: `<div style='...'>` -->
							<div> <!-- 2019-08-04 Original: `div.mapboxgl-map` -->
								<div></div> <!-- 2019-08-04 Original: `div.mapboxgl-canary` -->
								<div> <!-- 2019-08-04 Original: `div.mapboxgl-canvas-container` -->
									<canvas></canvas>
								</div>
								<div class='ikf-controls'> <!-- 2019-08-04 Original: `div.mapboxgl-control-container` -->
									<div class='ikf-top-left'></div>
									<div class='ikf-top-right'></div>
									<div class='ikf-bottom-left'>
										<div>
											<a
												aria-label='Mapbox logo'
												href='https://www.mapbox.com'
												rel='noopener'
												target='_blank'
											></a>
										</div>
									</div>
									<div class='ikf-bottom-right'>
										<div>
											<div></div>
										</div>
									</div>
								</div>
							</div>
							<div> <!-- 2019-08-04 Original: `STUB` -->
								<div></div> <!-- 2019-08-04 Original: `STUB` -->
							</div>
							<div class='ikf-resize'> <!-- 2019-08-04 Original: `STUB` -->
								<div>
									<div></div>
								</div>
								<div></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class='ikf-label'></div> <!-- 2019-08-04 Original: `.b-editor-map__desc` -->
	</div>
	<div class='ikf-mobile-hint'>You can <span>map using standard gestures</span></div>
</article>