<?php use Inkifi\Map\HTML; ?>
<form> <!-- 2019-08-05 Original: `form.o-editor__sidebar` -->
	<div class='ikf-sidebar-wide'> <!-- 2019-08-05 Original: `div.b-sidebar` -->
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Location</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
					<input type='text'/>
					<div class='ikf-placeholder'>Enter city of place</div>
				</div>
				<button class='ikf-location'>
					<div><?= df_block_output(null, 'Inkifi_Map::create/i/form/location.phtml') ?></div>
				</button>
			</div>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Labels</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<input type='text' value='London'/>
				<div class='ikf-placeholder'>Header</div>
			</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<input type='text' value='United Kingdom'/>
				<div class='ikf-placeholder'>Divider</div>
			</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<input type='text' value='51.496°N/-0.077°E'/>
				<div class='ikf-placeholder'>Tag line</div>
				<button class='ikf-location'>
					<div><?= df_block_output(null, 'Inkifi_Map::create/i/form/location.phtml') ?></div>
				</button>
			</div>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Size</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<div> <!-- 2019-08-06 Original: `div.b-radio-select` -->
					<div class='ikf-tabs'> <!-- 2019-08-06 Original: `div.b-radio-select__list` -->
						<?= df_cc_n(df_map(function($v) {return
							df_tag('div', [],
								df_tag('label', [], [
									df_tag('input', ['name' => 'size', 'type' => 'radio', 'value' => $v])
									,df_tag('span', [], $v)
									,df_tag('div')
								])
							)
						;}, ['12×16in', '18×24in', '20×28in', '24×36in', '28×40in'])) ?>
					</div>
				</div>
			</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<div> <!-- 2019-08-06 Original: `div.b-radio-select` -->
					<div class='ikf-tabs'> <!-- 2019-08-06 Original: `div.b-radio-select__list` -->
						<div> <!-- 2019-08-06 Original: `div.b-radio-select__item` -->
							<label>
								<input name='orientation' type='radio' value='Portrait'/>
								<span>Portrait</span>
								<div></div>
							</label>
						</div>
						<div> <!-- 2019-08-06 Original: `div.b-radio-select__item` -->
							<label>
								<input name='orientation' type='radio' value='Landscape'/>
								<span>Landscape</span>
								<div></div>
							</label>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Style</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<div class='ikf-tiles'> <!-- 2019-08-06 Original: `div.b-radio-tile-select` -->
					<?= HTML::tiles('style', ['contrast', 'twilight', 'bauhaus', 'sierra', 'spot']) ?>
				</div>
			</div>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Frame</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<div> <!-- 2019-08-06 Original: `div.b-radio-select` -->
					<div class='ikf-tabs'> <!-- 2019-08-06 Original: `div.b-radio-select__list` -->
						<div> <!-- 2019-08-06 Original: `div.b-radio-select__item` -->
							<label>
								<input name='frame' type='radio' value='Poster'/>
								<span>Paper poster</span>
								<div></div>
							</label>
						</div>
						<div> <!-- 2019-08-06 Original: `div.b-radio-select__item` -->
							<label>
								<input name='frame' type='radio' value='Canvas'/>
								<span>Canvas</span>
								<span>+£30</span>
								<div></div>
							</label>
						</div>
						<div> <!-- 2019-08-06 Original: `div.b-radio-select__item` -->
							<label>
								<input name='frame' type='radio' value='Frame'/>
								<span>Poster + frame</span>
								<span>+£30</span>
								<div></div>
							</label>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<div class='ikf-tiles'> <!-- 2019-08-06 Original: `div.b-radio-tile-select` -->
					<?= HTML::tiles('frame', ['natural', 'black', 'white']) ?>
				</div>
			</div>
		</section>
	</div>
	<div class='ikf-sidebar-sticky'> <!-- 2019-08-06 Original: `div.b-sidebar__sticky` -->
		<div> <!-- 2019-08-06 Original: `div.b-sidebar__mobile-nav` -->
			<div> <!-- 2019-08-06 Original: `div.b-sidebar-nav` -->
				<a href='javascript:void(0)'>Location</a>
				<a href='javascript:void(0)'>Labels</a>
				<a href='javascript:void(0)'>Size</a>
				<a href='javascript:void(0)'>Style</a>
				<a href='javascript:void(0)'>Frame</a>
			</div>
		</div>
		<button>
			<div class='ikf-label'>Buy poster</div>
			<div class='ikf-price'>£25</div>
		</button>
	</div>
</form>