<?php use Inkifi\Map\HTML; ?>
<form> <!-- 2019-08-05 Original: `form.o-editor__sidebar` -->
	<div class='ikf-sidebar-wide'> <!-- 2019-08-05 Original: `div.b-sidebar` -->
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Location</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
					<!--<input data-bind='dfHasValue, textInput: locationS' name='locationS' type='text'/>-->
<!-- 2019-08-30
I use `value` instead of `textInput` to prevent live updates: https://stackoverflow.com/a/26889303 -->
					<input data-bind='dfHasValue, value: locationS' name='locationS' type='text'/>
					<div class='ikf-placeholder'>Enter city of place</div>
				</div>
<!-- 2019-08-30 The button below does not have any sense. -->
				<?php /*echo df_block_output(null, 'Inkifi_Map::create/form/location.phtml')*/ ?>
			</div>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Labels</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<input data-bind='dfHasValue, textInput: h1' name='h1' type='text'/>
				<div class='ikf-placeholder'>Header</div>
			</div>
			<div class='ikf-row'> <!-- 2019-08-06 Original: `div.b-input__input-row` -->
				<input data-bind='dfHasValue, textInput: h2' name='h2' type='text'/>
				<div class='ikf-placeholder'>Divider</div>
			</div>
			<div class='ikf-row'>
<!-- 2019-08-06 Original: `div.b-input__input-row`
2019-08-27 https://knockoutjs.com/documentation/textinput-binding.html -->
				<input data-bind='dfHasValue, textInput: h3' name='h3' type='text'/>
				<div class='ikf-placeholder'>Tag line</div>
				<?= df_block_output(null, 'Inkifi_Map::create/form/location.phtml') ?>
			</div>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Size</div>
			<?= HTML::tabs('size', ['12×16in', '18×24in', '20×28in', '24×36in', '28×40in'])
				. HTML::tabs('orientation', ['Portrait', 'Landscape']) ?>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Style</div>
			<?= HTML::tiles('style', [
				'contrast', 'twilight', 'bauhaus', 'sierra', 'seaside' => 'spot'
			]) ?>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<!-- 2019-08-06 Original: `div.b-input__label.b-input__label--hidden-mobile` -->
			<div class='ikf-label'>Frame</div>
			<?= HTML::tabs('frame', [
				'Poster' => 'Paper poster', 'Canvas' => ['Canvas', '+£30'], 'Frame' => ['Poster + frame', '+£30']
			]) ?>
		</section>
		<section> <!-- 2019-08-06 Original: `div.b-input.b-input--hidden-mobile` -->
			<?= HTML::tiles('color', ['natural', 'black', 'white'], "enable: 'Frame' === frame()") ?>
		</section>
	</div>
	<div class='ikf-sidebar-sticky'> <!-- 2019-08-06 Original: `div.b-sidebar__sticky` -->
		<div> <!-- 2019-08-06 Original: `div.b-sidebar__mobile-nav` -->
			<nav> <!-- 2019-08-06 Original: `div.b-sidebar-nav` -->
				<?= df_cc_n(array_map(function($l) {return df_tag_a(
					$l, 'javascript:void(0)'
				);}, ['Location', 'Labels', 'Size', 'Style', 'Frame'])) ?>
			</nav>
		</div>
<!-- 2019-08-31
1) I defined a handler to prevent the form's submision on the `Enter` key press.
2) I replaced `button` with `div` to prevent the `click` handling on the `Enter` key press.
-->
		<div class='ikf-button' data-bind='click: buy'>
			<div>Buy poster</div>
			<div>£25</div>
		</div>
	</div>
</form>