<form> <!-- 2019-08-05 Original: `form.o-editor__sidebar` -->
	<div class='ikf-sidebar-wide'> <!-- 2019-08-05 Original: `div.b-sidebar` -->
		<section>
			<h3>Location</h3>
			<div>
				<div>
					<input type='text'/>
					<div>Enter city of place</div>
				</div>
				<button>
					<div><?= df_block_output(null, 'Inkifi_Map::create/i/form/location.phtml') ?></div>
				</button>
			</div>
		</section>
		<section>
			<h3>Labels</h3>
			<div>
				<input type='text' value='London'/>
				<div>Header</div>
			</div>
			<div>
				<input type='text' value='United Kingdom'/>
				<div>Divider</div>
			</div>
			<div>
				<input type='text' value='51.496°N/-0.077°E'/>
				<div>Tag line</div>
				<button>
					<div><?= df_block_output(null, 'Inkifi_Map::create/i/form/location.phtml') ?></div>
				</button>
			</div>
		</section>
		<section>
			<h3>Size</h3>
			<div>
				<div>
					<div>
						<div>
							<label>
								<input name='size' type='radio' value='12×16in'/>
								<span>12×16in</span>
								<div></div>
							</label>
						</div>
						<div>
							<label>
								<input name='size' type='radio' value='18×24in'/>
								<span>18×24in</span>
								<div></div>
							</label>
						</div>
						<div>
							<label>
								<input name='size' type='radio' value='20×28in'/>
								<span>20×28in</span>
								<div></div>
							</label>
						</div>
						<div>
							<label>
								<input name='size' type='radio' value='24×36in'/>
								<span>24×36in</span>
								<div></div>
							</label>
						</div>
						<div>
							<label>
								<input name='size' type='radio' value='28×40in'/>
								<span>28×40in</span>
								<div></div>
							</label>
						</div>
					</div>
				</div>
			</div>
			<div>
				<div>
					<div>
						<div>
							<label>
								<input name='orientation' type='radio' value='Portrait'/>
								<span>Portrait</span>
								<div></div>
							</label>
						</div>
						<div>
							<label>
								<input name='orientation' type='radio' value='Landscape'/>
								<span>Landscape</span>
								<div></div>
							</label>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section>
			<h3>Style</h3>
			<div>
				<div>
					<?=
						df_cc_n(df_map(function($v) {$t = ucfirst($v); return
							df_tag('div', [],
								df_tag('label', [], [
									df_tag('input', ['name' => 'style', 'type' => 'radio', 'value' => $v])
									,df_tag('div', [], [
										df_tag('div', [],
											df_block_output(null, "Inkifi_Map::create/i/form/style/$v.phtml")
										)
										,df_tag('div')
									])
									,df_tag('span', [], $t)
								])
							)
						;}, ['contrast', 'twilight', 'bauhaus', 'sierra', 'seaside']))
					?>
				</div>
			</div>
		</section>
		<section>
			<h3>Frame</h3>
			
		</section>
		<section>
		</section>
	</div>
	<div class='ikf-sidebar-small'> <!-- 2019-08-05 Original: `div.b-sidebar__sticky` -->
		<div> <!-- 2019-08-05 Original: `div.b-sidebar__mobile-nav` -->
			<div> <!-- 2019-08-05 Original: `div.b-sidebar-nav` -->
				<a href='javascript:void(0)'>Location</a>
				<a href='javascript:void(0)'>Labels</a>
				<a href='javascript:void(0)'>Size</a>
				<a href='javascript:void(0)'>Style</a>
				<a href='javascript:void(0)'>Frame</a>
			</div>
		</div>
		<button>
			<div class='ikf-label'>Buy poster</div>
			<div class='ikf-price'>£25</div>
		</button>
	</div>
</form>