<!-- 2019-08-27 I added `style='display:none'` to prevent images flickering before the carousel's initialization. -->
<div class='ikf-cities' style='display:none'>
	<?=
		df_cc_n(df_map_k(
			function($c, array $q) {return df_tag('a',
				['href' => ikf_map_url_create($q)]
				,df_tag('img', ['src' => df_asset_url("Inkifi_Map::i/index/map/$c.jpg")])
			);}
			,df_map(function($v) {return array_combine(['latitude', 'longitude', 'style', 'zoom'], $v);}, [
				'new-york' => [40.713, -74.006, 'Contrast', 10.7]
				,'singapore' => [1.320, 103.852, 'Sierra', 10.4]
				,'copenhagen' => [55.687, 12.570, 'Bauhaus', 10.1]
				,'paris' => [48.857, 2.351, 'Contrast', 10.4]
				,'lisbon' => [38.708, -9.137, 'Seaside', 10.1]
				,'london' => [51.488, -0.075, 'Contrast', 9.8]
				,'amsterdam' => [ 52.375, 4.898, 'Sierra', 10.4]
			])
		));
	?>
</div>