<div class='ikf-row'>
	<div class='ikf-figure'>
		<div>
			<?= df_tag('img', ['src' => df_asset_url('Inkifi_Map::i/index/header/yellow.svg')]) ?>
		</div>
	</div>
</div>
<div class='ikf-row'>
	<div class='ikf-left'>
		<h1>Mappy Place</h1>
		<div class='ikf-subtitle e1'>Create and customise city map prints of anywhere in the world</div>
		<div class='ikf-subtitle e2'>Free And Fast UK Delivery</div>
		<a class='ikf-create' href='javascript:void(0)'>Create Your Poster</a>
	</div>
	<div class='ikf-right'></div>
</div>