<div class='ikf-row'>
	<figure>
		<div><?= df_tag('img', ['src' => df_asset_url('Inkifi_Map::index/i/header/yellow.svg')]) ?></div>
	</figure>
	<?= df_cc_n(df_map(function($i) {return df_tag('figure', [], df_tag('div', [], df_block_output(null,
		"Inkifi_Map::index/i/header/$i.phtml"
	)));}, ['green', 'violet'])) ?>
</div>
<div class='ikf-row'>
	<div class='ikf-left'>
		<h1>Mappy Place</h1>
		<div class='ikf-subtitle e1'>Create and customise city map prints of anywhere in the world</div>
		<div class='ikf-subtitle e2'>Free And Fast UK Delivery</div>
		<a class='ikf-create' href='javascript:void(0)'>Create Your Poster</a>
	</div>
	<figure>
		<div>
			<?= df_block_output(null, 'Inkifi_Map::index/i/header/orange.phtml') ?>
		</div>
	</figure>
	<figure>
		<div>
			<?= df_block_output(null, 'Inkifi_Map::index/i/header/black.phtml') ?>
		</div>
	</figure>
</div>