<ol class='ikf-benefits'>
	<li>
		<div class='ikf-benefit'>
			<div class='ikf-figure'><?= df_block_output(null, 'Inkifi_Map::index/i/shipping.phtml') ?></div>
			<div>Fast shipping, worldwide</div>
		</div>
	</li>
	<li>
		<div class='ikf-benefit'>
			<div class='ikf-figure'>
				<?= df_tag('img', ['src' => df_asset_url('Inkifi_Map::index/i/print.svg')]) ?>
			</div>
			<div class='ikf-title'>Premium Quality Prints</div>
		</div>
	</li>
	<li>
		<div class='ikf-benefit'>
			<div class='ikf-figure'><?= df_block_output(null, 'Inkifi_Map::index/i/guarantee.phtml') ?></div>
			<div>100% Satisfaction Guarantee</div>
		</div>
	</li>
</ol>
<h2>Create Your Poster</h2>
<div class='ikf-cities'>
	<?=
		df_cc_n(df_map(function($c) {return
			df_tag('a', ['href' => 'javascript:void(0)'],
				df_tag('img', ['src' => df_asset_url("Inkifi_Map::index/i/map/$c.jpg")])
			)
		;}, ['new-york', 'singapore', 'copenhagen', 'paris', 'lisbon', 'london', 'amsterdam']));
	?>
</div>
<div class='ikf-button-container'>
	<a class='ikf-create' href='javascript:void(0)'>Create Poster</a>
</div>