<ol class='ikf-benefits'>
	<li>
		<div class='ikf-benefit'>
			<div class='ikf-figure'><?= df_block_output(null, 'Inkifi_Map::i/index/shipping.phtml') ?></div>
			<div>Fast shipping, worldwide</div>
		</div>
	</li>
	<li>
		<div class='ikf-benefit'>
			<div class='ikf-figure'>
				<?= df_tag('img', ['src' => df_asset_url('Inkifi_Map::i/index/print.svg')]) ?>
			</div>
			<div class='ikf-title'>Premium Quality Prints</div>
		</div>
	</li>
	<li>
		<div class='ikf-benefit'>
			<div class='ikf-figure'><?= df_block_output(null, 'Inkifi_Map::i/index/guarantee.phtml') ?></div>
			<div>100% Satisfaction Guarantee</div>
		</div>
	</li>
</ol>
<h2>Create Your Poster</h2>
<?= df_block_output(null, 'Inkifi_Map::index/section/2/cities.phtml') ?>
<div class='ikf-button-container'>
	<a class='ikf-create' href='javascript:void(0)'>Create Poster</a>
</div>